version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # We want to be more sure in our e2e-test, before committing to
  # update all of our dependencies.
  # Only add packages very sporadically here for now.
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/zellij-utils/"
    schedule:
      interval: "daily"



